version: '3'

services:
  search-api:
    image: bitnami/postgresql:15.7.0
    container_name: search-db
    ports:
      - 5432:5432
    env_file:
      - ./.env
    volumes:
      - ./databaseV2:/bitnami/postgresql